name: environment-variables
variables:
  - name: baseUrl
    value: http://api.openweathermap.org/data/3.0
  - name: station-name
    value: San Francisco Test Station
  - name: external-id
    value: "SF_TEST001 "
  - name: latitude
    value: "37.76"
  - name: longitude
    value: "-122.43"
  - name: altitude
    value: "150"
  - name: update-station-name
    value: San Francisco Updated Station
  - name: update-external-id
    value: SF_UPD001
  - name: update-latitude
    value: "37.80"
  - name: update-longitude
    value: "-122.47"
  - name: update-altitude
    value: "143"
  - secret: true
    name: api-key
  - name: stationId
    value: 6a953d6aadde3b00013441fa
