info:
  name: environment-variables
  type: environment
variables:
  baseUrl: "http://api.openweathermap.org/data/3.0"
  "station-name": "San Francisco Test Station"
  "external-id": "SF_TEST001 "
  latitude: "37.76"
  longitude: "-122.43"
  altitude: "150"
  "update-station-name": "San Francisco Updated Station"
  "update-external-id": "SF_UPD001"
  "update-latitude": "37.80"
  "update-longitude": "-122.47"
  "update-altitude": "143"
  api-key: "${{ secrets.OPENWEATHER_API_KEY }}"
  stationId: "6a953d6aadde3b00013441fa"
